---
title: Code For Worcester
timezone: UTC
markdown: kramdown
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  rooms:
    title: Rooms
    output: true
email: hello@codeforworcester.org
description:
  'Part of the Code for America Brigade network, we are a volunteer group
  of developers, designers, data geeks, and citizen activists who use creative technology
  to solve civic and social problems.'
baseurl: ''
url: https://www.codeforworcester.org
# NOTE:If you change the below donate_url you should also update the URL here: https://github.com/codeforworcester/.github/FUNDING.yml
donate_url: https://codeforamerica.org/donate-to-a-brigade?utm_campaign=Code%20for%20Worcester&utm_source=codeforworcester.org
github_url: https://github.com/code-for-worcester
meetup_url: https://www.meetup.com/code-for-worcester/
zoom_url: https://codeforamerica.zoom.us/meeting/register/tJEocO6prD4tEtxyZTta2yRj4V9XcKJvcBPP
slack_url: https://communityinviter.com/apps/codeforworcester/code-for-worcester
slack_team_id: T01T64R4SJU

boston_url: https://www.codeforboston.org/
boston_github_url: https://github.com/codeforboston

plugins:
  - jekyll-redirect-from
